In [2]:
import quantecon as qe
import numpy as np
import pandas as pd

In [3]:
p1 = np.array([[0.1, 0.5, 0.4], 
      [0.3,   0.3,  0.4], 
      [0.8,   0.1,   0.1]])

p2 = np.array([[0.1, 0.5, 0.4], 
      [0.3,   0.3,  0.4], 
      [0.8,   0,   0.2]])

p3 = np.array([[0.5, 0, 0.5], 
      [0.05,   0.05,  0.9], 
      [0.05,   0.9,   0.05]])

p4 = np.array([[1/3, 1/3,1/3], 
      [1/3,   1/3,  1/3], 
      [1/3,   1/3,   1/3]])

pi=[[1, 0, 0]]



In [4]:
# p1=[*zip(*p1)]
# p2=[*zip(*p2)]
# p3=[*zip(*p3)]
# p4=[*zip(*p4)]
# print(p1, 'P1')
# print(p2, 'P2')
# print(p3, 'P3')
# print(p4, 'P4')

In [5]:
p1=np.array(p1)
p2=np.array(p2)
p3=np.array(p3)
p4=np.array(p4)
print(p1, 'P1')
print(p2, 'P2')
print(p3, 'P3')
print(p4, 'P4')


[[0.1 0.5 0.4]
 [0.3 0.3 0.4]
 [0.8 0.1 0.1]] P1
[[0.1 0.5 0.4]
 [0.3 0.3 0.4]
 [0.8 0.  0.2]] P2
[[0.5  0.   0.5 ]
 [0.05 0.05 0.9 ]
 [0.05 0.9  0.05]] P3
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]] P4


In [6]:
from itertools import *

In [7]:
mcp1 = qe.MarkovChain(p1)
mcp2 = qe.MarkovChain(p2)
mcp3 = qe.MarkovChain(p3)
mcp4 = qe.MarkovChain(p4)

print(mcp1, "MC p1")
print(mcp2, "MC p2")
print(mcp3, "MC p3")
print(mcp4, "MC p4")

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.1 0.5 0.4]
 [0.3 0.3 0.4]
 [0.8 0.1 0.1]]> MC p1
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.1 0.5 0.4]
 [0.3 0.3 0.4]
 [0.8 0.  0.2]]> MC p2
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.5  0.   0.5 ]
 [0.05 0.05 0.9 ]
 [0.05 0.9  0.05]]> MC p3
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]> MC p4


In [8]:
#симулиция последовательности, длина 1000
s = np.array([1,1,3,2,3,1])
print(s, "Последовательность")

[1 1 3 2 3 1] Последовательность


In [9]:
# array=np.column_stack((a1, a2,a3,a4,a5,a6,a7,a8,a9,a10))

In [10]:
# df = pd.DataFrame(array)

# df[0]=[1,0,0,2,1,2,1,2,0,3]
# display(df.head(20))

In [11]:
# #Расчет вектора альфа методом Рабинера
# alfa= np.zeros((10, 4))
# alfa

In [12]:

# beta=np.array([[0.0,0.0,0.0,0.0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0],
#             [0,0,0,0]])

# beta

In [13]:
# pi=np.array([1/4,    1/4,  1/4,    1/4])
# pi

In [14]:
#  df[0].iloc[1:]


In [15]:
# k=df.loc[0][0]    
# print(k,"K", '\n')
# print(pi[k], "Pi", '\n')

# alfa[0][1]=pi[k]

# print(alfa, 'alfa')

In [16]:
alfa1= np.zeros((4,3))
alfa2= np.zeros((4, 3))
alfa3= np.zeros((4, 3))
alfa4= np.zeros((4, 3))
alfa5= np.zeros((4, 3))
alfa6= np.zeros((4, 3))
alfa1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# print(s, 'S')
# print(s[1:6], "s 1-6")

for i in s[1:6]:  
    print(i)

print(pi[0])

1
3
2
3
1
[1, 0, 0]


In [29]:
# alfa[2][1]
# alfa2[j]="%.3f" % np.dot(alfa1[j], p1[s[1]-1])
# alfa2[0]="%.3f" % np.dot(alfa2[0], p1[s[1]])

alfa2[0][0]="%.3f" % np.dot(alfa1[0], p1[0])
print(alfa2)

[[0.1 0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]]


In [27]:
alfa2= np.zeros((4, 3))
# alfa2[0][0][0]="%.3f" % np.dot(alfa1[0], p1[0])
# alfa2[1][0][0]="%.3f" % np.dot(alfa1[0], p2[0])
print(alfa2[0][0])

0.0


In [28]:
"%.3f" % np.dot(alfa3[2-1], p3[:,1])

'0.036'

In [21]:
def vecalfa():

    k=s[0]
    for i in range(1,7):
        if i == 1:
            for j in range(0,4):
                alfa1[j]=pi[0]
#             print(alfa1)
            
        if i == 2:
            k=s[i-1]-1
            for j in range(0,4):
                if j == 0:
                    alfa2[j][k]="%.3f" % np.dot(alfa1[j], p1[:,k])
                if j == 1:
                    alfa2[j][k]="%.3f" % np.dot(alfa1[j], p2[:,k])
                if j == 2:
                    alfa2[j][k]="%.3f" % np.dot(alfa1[j], p3[:,k])
                if j == 3:
                    alfa2[j][k]="%.3f" % np.dot(alfa1[j], p4[:,k])
                
#             print(alfa2)
            
        if i == 3:

            k=s[i-1]-1
            print(k)
            for j in range(0,4):
                if j == 0:
                    alfa3[j][k]="%.3f" % np.dot(alfa2[j], p1[:,k])
                if j == 1:
                    alfa3[j][k]="%.3f" % np.dot(alfa2[j], p2[:,k])
                if j == 2:
                    alfa3[j][k]="%.3f" % np.dot(alfa2[j], p3[:,k])
                if j == 3:
                    alfa3[j][k]="%.3f" % np.dot(alfa2[j], p4[:,k])
                
#             print(alfa3)
           
        if i == 4:

            k=s[i-1]-1
            for j in range(0,4):
                if j == 0:
                    alfa4[j][k]="%.3f" % np.dot(alfa3[j], p1[:,k])
                if j == 1:
                    alfa4[j][k]="%.3f" % np.dot(alfa3[j], p2[:,k])
                if j == 2:
                    alfa4[j][k]="%.3f" % np.dot(alfa3[j], p3[:,k])
                if j == 3:
                    alfa4[j][k]="%.3f" % np.dot(alfa3[j], p4[:,k])
                
#             print(alfa4)  
        if i == 5:

            k=s[i-1]-1
            for j in range(0,4):
                if j == 0:
                    alfa5[j][k]="%.3f" % np.dot(alfa4[j], p1[:,k])
                if j == 1:
                    alfa5[j][k]="%.3f" % np.dot(alfa4[j], p2[:,k])
                if j == 2:
                    alfa5[j][k]="%.3f" % np.dot(alfa4[j], p3[:,k])
                if j == 3:
                    alfa5[j][k]="%.3f" % np.dot(alfa4[j], p4[:,k])
                
#             print(alfa5)  
        if i == 6:
            k=s[i-1]-1
            for j in range(0,4):
                if j == 0:
                    alfa6[j][k]="%.3f" % np.dot(alfa5[j], p1[:,k])
                if j == 1:
                    alfa6[j][k]="%.3f" % np.dot(alfa5[j], p2[:,k])
                if j == 2:
                    alfa6[j][k]="%.3f" % np.dot(alfa5[j], p3[:,k])
                if j == 3:
                    alfa6[j][k]="%.3f" % np.dot(alfa5[j], p4[:,k])
                
#             print(alfa6)  

    print(alfa1, '\n', alfa2,'\n', alfa3, '\n', alfa4,'\n', alfa5,'\n', alfa6 )
    return [alfa1,alfa2,alfa3,alfa4,alfa5,alfa6]
          
vecalfa()


2
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]] 
 [[0.1   0.    0.   ]
 [0.1   0.    0.   ]
 [0.5   0.    0.   ]
 [0.333 0.    0.   ]] 
 [[0.    0.    0.04 ]
 [0.    0.    0.04 ]
 [0.    0.    0.25 ]
 [0.    0.    0.111]] 
 [[0.    0.004 0.   ]
 [0.    0.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.037 0.   ]] 
 [[0.    0.    0.002]
 [0.    0.    0.   ]
 [0.    0.    0.203]
 [0.    0.    0.012]] 
 [[0.002 0.    0.   ]
 [0.    0.    0.   ]
 [0.01  0.    0.   ]
 [0.004 0.    0.   ]]


[array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]]), array([[0.1  , 0.   , 0.   ],
        [0.1  , 0.   , 0.   ],
        [0.5  , 0.   , 0.   ],
        [0.333, 0.   , 0.   ]]), array([[0.   , 0.   , 0.04 ],
        [0.   , 0.   , 0.04 ],
        [0.   , 0.   , 0.25 ],
        [0.   , 0.   , 0.111]]), array([[0.   , 0.004, 0.   ],
        [0.   , 0.   , 0.   ],
        [0.   , 0.225, 0.   ],
        [0.   , 0.037, 0.   ]]), array([[0.   , 0.   , 0.002],
        [0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.203],
        [0.   , 0.   , 0.012]]), array([[0.002, 0.   , 0.   ],
        [0.   , 0.   , 0.   ],
        [0.01 , 0.   , 0.   ],
        [0.004, 0.   , 0.   ]])]

In [22]:
# print(alfa2[2])
# print(p3[:,2])
# print(alfa3)
# print(p3)
# "%.3f" % np.dot(alfa2[2], p3[:,1])

In [23]:
# ii=[0,1,2,3,4,5,6,7,8,9]

# for d in ii:
#         vecalfa(d)
#         print(alfa) 
        

In [24]:
# ii=[0,1,2,3,4,5,6,7,8,9]
# j=0
# for d in ii:
   
#     for i in df[d].iloc[1:]:    

#         alfa[j,i]=np.dot(alfa[j], tvt[i])
#         j=j+1
#     d=d+1   
# alfa   


In [25]:
import numpy as np
 
class MarkovChain(object):
    def __init__(self, transition_prob):
      
        self.transition_prob = transition_prob
        self.states = list(transition_prob.keys())
 
    def next_state(self, current_state):
        
        next_ = np.random.choice(self.states, p = [
              self.transition_prob[current_state][next_state] 
               for next_state in self.states]
        )
        return next_
 
    def generate_states(self, current_state, no=10):
      
        future_states = []
        for i in range(no):
            next_state = self.next_state(current_state)
            future_states.append(next_state)
            current_state = next_state

        return ''.join(future_states)

In [26]:
def MarkovMatrix(n = 26):

    np.random.seed(0) # for replicability
    symbols = [chr(i+65) for i in range(n)] # list of available symbols

    markov_matrix = {}
    for i, s in enumerate(symbols):
        dim = len(symbols)

        probs = np.random.random(dim*3) 
        probs.sort()
        probs = np.append(probs[dim%2::2], probs[::-2])
        offset = -int(dim*1.5)
        probs = np.roll(probs, offset+i)[:dim] 
        probs /= probs.sum()
    
        markov_matrix[s] = {s: p for s, p in zip(symbols, probs)}
        print(markov_matrix[s])

    print(markov_matrix)
    
    return markov_matrix