Этапы эксперимента:
1. генерация подклассов матриц ТВ, ТН, БП, БЛ q=4
2. генерация подклассов k=q^b
3. генерация последовательностей 5 последовательностей B=5
4. функция расчета вектора a (метод рабинера)
5. формирование датасета b^k векторов

In [1]:
import quantecon as qe
import numpy as np
import pandas as pd

In [2]:
tv = np.array([[0.25, 0.25, 0.25, 0.25], 
      [1/3,   1/3,  1/3,  0], 
      [0.5,   0.5,   0,   0],
      [0.5,   0,     0,   0.5]])

tn = np.array( [[0.5,  0,     0,    0.5], 
      [0,    0,     0.5,  0.5],
      [0,    1/3,   1/3,  1/3],
      [0.25, 0.25, 0.25, 0.25]])

bp =  np.array( [[0,      0,    0.5,   0.5],
                [0,      0,     0.5,   0.5],
                [0.5,    0.5,   0,    0], 
                [0.5,    0.5,   0,    0]])

bl =   np.array([[0.5,    0.5, 0,    0], 
      [0.5,    0.5,  0,    0],
      [0,      0,    0.5,   0.5],
      [0,      0,    0.5,   0.5]])

In [3]:
tvt=[*zip(*tv)]
tvt

[(0.25, 0.3333333333333333, 0.5, 0.5),
 (0.25, 0.3333333333333333, 0.5, 0.0),
 (0.25, 0.3333333333333333, 0.0, 0.0),
 (0.25, 0.0, 0.0, 0.5)]

In [4]:
tvt=np.array(tvt)
tvt

array([[0.25      , 0.33333333, 0.5       , 0.5       ],
       [0.25      , 0.33333333, 0.5       , 0.        ],
       [0.25      , 0.33333333, 0.        , 0.        ],
       [0.25      , 0.        , 0.        , 0.5       ]])

In [5]:
pi=[[1/4,    1/4,  1/4,    1/4]]
pi

[[0.25, 0.25, 0.25, 0.25]]

In [6]:
from itertools import *

In [7]:
#комбинации классов 
for i in combinations_with_replacement(['tv','tn','bp','pl'], 4):
    print(i, end=' ') 

('tv', 'tv', 'tv', 'tv') ('tv', 'tv', 'tv', 'tn') ('tv', 'tv', 'tv', 'bp') ('tv', 'tv', 'tv', 'pl') ('tv', 'tv', 'tn', 'tn') ('tv', 'tv', 'tn', 'bp') ('tv', 'tv', 'tn', 'pl') ('tv', 'tv', 'bp', 'bp') ('tv', 'tv', 'bp', 'pl') ('tv', 'tv', 'pl', 'pl') ('tv', 'tn', 'tn', 'tn') ('tv', 'tn', 'tn', 'bp') ('tv', 'tn', 'tn', 'pl') ('tv', 'tn', 'bp', 'bp') ('tv', 'tn', 'bp', 'pl') ('tv', 'tn', 'pl', 'pl') ('tv', 'bp', 'bp', 'bp') ('tv', 'bp', 'bp', 'pl') ('tv', 'bp', 'pl', 'pl') ('tv', 'pl', 'pl', 'pl') ('tn', 'tn', 'tn', 'tn') ('tn', 'tn', 'tn', 'bp') ('tn', 'tn', 'tn', 'pl') ('tn', 'tn', 'bp', 'bp') ('tn', 'tn', 'bp', 'pl') ('tn', 'tn', 'pl', 'pl') ('tn', 'bp', 'bp', 'bp') ('tn', 'bp', 'bp', 'pl') ('tn', 'bp', 'pl', 'pl') ('tn', 'pl', 'pl', 'pl') ('bp', 'bp', 'bp', 'bp') ('bp', 'bp', 'bp', 'pl') ('bp', 'bp', 'pl', 'pl') ('bp', 'pl', 'pl', 'pl') ('pl', 'pl', 'pl', 'pl') 

In [61]:
mc1 = qe.MarkovChain(tv)

mc2 = qe.MarkovChain(tn)
mc3 = qe.MarkovChain(bp)
mc4 = qe.MarkovChain(bl)

print(mc1)
print(mc2)
print(mc3)
print(mc4)

<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.25       0.25       0.25       0.25      ]
 [0.33333333 0.33333333 0.33333333 0.        ]
 [0.5        0.5        0.         0.        ]
 [0.5        0.         0.         0.5       ]]>
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.5        0.         0.         0.5       ]
 [0.         0.         0.5        0.5       ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.25       0.25       0.25       0.25      ]]>
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.  0.  0.5 0.5]
 [0.  0.  0.5 0.5]
 [0.5 0.5 0.  0. ]
 [0.5 0.5 0.  0. ]]>
<bound method MarkovChain.__repr__ of Markov chain with transition matrix 
P = 
[[0.5 0.5 0.  0. ]
 [0.5 0.5 0.  0. ]
 [0.  0.  0.5 0.5]
 [0.  0.  0.5 0.5]]>


In [9]:
#симулиция последовательности, длина 1000
a2=mc1.simulate(10, random_state=None)
display(a2)

array([2, 1, 2, 1, 2, 0, 2, 1, 1, 1])

In [10]:
#симулиция последовательности, длина 1000
a1=mc1.simulate(10, random_state=None)
a2=mc1.simulate(10, random_state=None)
a3=mc1.simulate(10, random_state=None)
a4=mc1.simulate(10, random_state=None)
a5=mc1.simulate(10, random_state=None)
a6=mc1.simulate(10, random_state=None)
a7=mc1.simulate(10, random_state=None)
a8=mc1.simulate(10, random_state=None)
a9=mc1.simulate(10, random_state=None)
a10=mc1.simulate(10, random_state=None)

In [11]:
array=np.column_stack((a1, a2,a3,a4,a5,a6,a7,a8,a9,a10))

In [14]:
df = pd.DataFrame(array)

df[0]=[1,0,0,2,1,2,1,2,0,3]
display(df.head(20))

0  1  2  3  4  5  6  7  8  9
0  1  2  1  1  0  3  3  2  0  1
1  0  1  0  2  0  0  3  1  2  2
2  0  2  2  1  2  3  0  1  0  1
3  2  1  1  2  0  0  3  2  0  2
4  1  2  0  0  0  0  0  0  2  0
5  2  0  1  3  2  3  2  2  0  2
6  1  3  2  3  1  0  0  1  1  0
7  2  0  0  3  0  3  2  2  1  2
8  0  2  0  3  1  0  0  1  2  1
9  3  0  1  3  2  0  3  0  0  1

Пусть ('tv', 'tn', 'tn', 'bp')

In [24]:
#Расчет вектора альфа методом Рабинера
alfa= np.zeros((10, 4))


alfa


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:

beta=np.array([[0.0,0.0,0.0,0.0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0],
            [0,0,0,0]])

beta

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
pi=np.array([1/4,    1/4,  1/4,    1/4])
pi

array([0.25, 0.25, 0.25, 0.25])

In [18]:
 df[0].iloc[1:]


1    0
2    0
3    2
4    1
5    2
6    1
7    2
8    0
9    3
Name: 0, dtype: int64

In [25]:
k=df.loc[0][0]    
print(k,"K", '\n')
print(pi[k], "Pi", '\n')

alfa[0][1]=pi[k]

print(alfa, 'alfa')

1 K 

0.25 Pi 

[[0.   0.25 0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]] alfa


In [26]:
tvt

array([[0.25      , 0.33333333, 0.5       , 0.5       ],
       [0.25      , 0.33333333, 0.5       , 0.        ],
       [0.25      , 0.33333333, 0.        , 0.        ],
       [0.25      , 0.        , 0.        , 0.5       ]])

In [27]:
alfa[0]

array([0.  , 0.25, 0.  , 0.  ])

In [29]:
ii=[0,1,2,3,4,5,6,7,8,9]

for d in ii:
        k=df.loc[d][0]  
        print(k)
    

1
0
0
2
1
2
1
2
0
3


In [44]:
def vecalfa(n):
    alfa= np.zeros((10, 4))
    
    k=df.loc[0][n]    
#     print(k, 'K ', n)
    
    alfa[0,k]=pi[k]
#     print(alfa[0])
   
    j=1
    for i in df[n].iloc[1:]:    

        alfa[j,i]="%.3f" % np.dot(alfa[j-1], tvt[i])
        j=j+1

        
    return alfa
          
print(vecalfa(0))


[[0.    0.25  0.    0.   ]
 [0.083 0.    0.    0.   ]
 [0.021 0.    0.    0.   ]
 [0.    0.    0.005 0.   ]
 [0.    0.003 0.    0.   ]
 [0.    0.    0.001 0.   ]
 [0.    0.001 0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]]


In [45]:
# ii=[0,1,2,3,4,5,6,7,8,9]

# for d in ii:
#         vecalfa(d)
#         print(alfa) 
        

In [47]:
alfadf = pd.DataFrame(vecalfa(0))
alfadf


0      1      2    3
0  0.000  0.250  0.000  0.0
1  0.083  0.000  0.000  0.0
2  0.021  0.000  0.000  0.0
3  0.000  0.000  0.005  0.0
4  0.000  0.003  0.000  0.0
5  0.000  0.000  0.001  0.0
6  0.000  0.001  0.000  0.0
7  0.000  0.000  0.000  0.0
8  0.000  0.000  0.000  0.0
9  0.000  0.000  0.000  0.0

In [52]:
# ii=[0,1,2,3,4,5,6,7,8,9]
# j=0
# for d in ii:
   
#     for i in df[d].iloc[1:]:    

#         alfa[j,i]=np.dot(alfa[j], tvt[i])
#         j=j+1
#     d=d+1   
# alfa   


In [59]:
import numpy as np
 
class MarkovChain(object):
    def __init__(self, transition_prob):
      
        self.transition_prob = transition_prob
        self.states = list(transition_prob.keys())
 
    def next_state(self, current_state):
        
        next_ = np.random.choice(self.states, p = [
              self.transition_prob[current_state][next_state] 
               for next_state in self.states]
        )
        return next_
 
    def generate_states(self, current_state, no=10):
      
        future_states = []
        for i in range(no):
            next_state = self.next_state(current_state)
            future_states.append(next_state)
            current_state = next_state

        return ''.join(future_states)

In [60]:
def MarkovMatrix(n = 26):

    np.random.seed(0) # for replicability
    symbols = [chr(i+65) for i in range(n)] # list of available symbols

    markov_matrix = {}
    for i, s in enumerate(symbols):
        dim = len(symbols)

        probs = np.random.random(dim*3) 
        probs.sort()
        probs = np.append(probs[dim%2::2], probs[::-2])
        offset = -int(dim*1.5)
        probs = np.roll(probs, offset+i)[:dim] 
        probs /= probs.sum()
    
        markov_matrix[s] = {s: p for s, p in zip(symbols, probs)}
        print(markov_matrix[s])

    print(markov_matrix)
    
    return markov_matrix